### ISSUE TITLE
The service cannot be stopped even if the dependant service is stopped

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1610] opened 2023-11-25 17:01 UTC
**Describe the bug**
The service cannot be stopped even if the dependant service is stopped.

**Steps to reproduce**
1. Create three services: db, backend and frontend. The backend depends on the db, and the frontend depends on the backend;
2. Stop the frontend service;
3. Stop the backend service.

**Result**
<img width="1284" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/2d9483ce-cf66-4a1b-8823-e1790b29d87d">

**Expected behavior**

**Environment**
- Walrus version: v0.4.0-rc3

**Comment by gitlawr** [comment] 2023-11-26 01:56
duplicate of https://github.com/seal-io/walrus/issues/1575

**Comment by Finenyaco** [comment] 2023-11-28 04:49
Closed as completed

**Closed by Finenyaco** 2023-11-28 04:49 UTC
Labels: bug
