### ISSUE TITLE
When there are multiple dependent links and those services are in the stopped state, those services cannot be deleted

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1673] opened 2023-12-04 10:43 UTC
**Describe the bug**
When there are multiple dependent links and those services are in the stopped state, those services cannot be deleted.

**Steps to reproduce**
1. Create multiple services that have multiple dependent links;
2. Stop all services;
3. Delete all services.

**Result**
<img width="1217" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/7bfdc432-8d84-42e1-b9fc-5b96924e4533">
<img width="1279" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/6f2c66df-0c77-4fd3-8e50-8c450763c15d">

**Environment**
- Walrus version: v0.4.0

**Comment by gitlawr** [comment] 2023-12-04 10:52
Duplicate of https://github.com/seal-io/walrus/issues/1636

**Comment by Finenyaco** [comment] 2023-12-25 10:38
**Environment**
- Walrus version: main 8048eb2af52e636e42e656ee507d875cb83999d9
- UI version: dev-33d2ecd

**Test Result:** pass

**Closed by Finenyaco** 2023-12-25 10:38 UTC
Labels: bug
