### ISSUE TITLE
EnvironmentTypes dropdown menu not showing any value from the env create page

### ISSUE THREAD

**Issue by ajasonwang** [seal-io/walrus#1349] opened 2023-11-04 05:06 UTC
**Describe the bug**
EnvironmentTypes dropdown menu not showing any value from the env create page

**Steps to reproduce**
1. Go to create environment page such as: /app-management/project/485767661397999618/environment/edit
2. Try creating a new env

**Result**
EnvironmentTypes dropdown menu not showing any choice value, makes it unable to continue create the env.

**Expected behavior**
Dropdown menu should show the value like the following as the backend code indicates:
EnvironmentDevelopment,
EnvironmentStaging,
EnvironmentProduction,

**Environment**
- Walrus version:
- {commit: "96c9574ea9fee1bad195827be7db27d629f416a6", version: "dev"}

**Additional context**
no content

**Comment by ajasonwang** [comment] 2023-11-04 05:11
You can see the abnormal from F12 console, applicableEnvironmentType DO NOT HAVE a value: /v1/projects/485767661397999618/connectors?applicableEnvironmentType=&page=-1&withGlobal=true

**Comment by Finenyaco** [comment] 2023-11-06 02:17
Hi @ajasonwang , environment type was supported from 13aeb75d8617fbf87b3e0f298f85a8c91b784b42. The dev version is used for QA testing, and we recommend using the release version for trial purposes.

**Comment by Finenyaco** [comment] 2023-11-07 02:21
Close this issue as not a bug.

**Closed by Finenyaco** 2023-11-07 02:21 UTC
Labels: bug
