### ISSUE TITLE
Templates with duplicate names cause versions of different templates to be merged

### ISSUE THREAD

**Issue by linyinli** [seal-io/walrus#1854] opened 2024-01-10 04:17 UTC
**Describe the bug**
Templates with duplicate names cause versions of different templates to be merged.

**Steps to reproduce**
1. Add a catalog: https://github.com/alibabacloud-automation;
2. View the template: alicloud-rds-mysql, due to the same name: terraform-alicloud-rds-mysql, these versions of the template are merged into the existing template.

**Result**
<img width="1838" alt="image" src="https://github.com/seal-io/walrus/assets/42955482/39eae430-f0a0-46f2-9d60-702345bcb3e8">

**Expected behavior**
Split into two templates.

**Environment**
- Walrus version: 
  - UI: dev-437b352
  - Server: dev-71aeab4

**Comment by Finenyaco** [comment] 2024-01-10 06:15
Duplicate of https://github.com/seal-io/walrus/issues/1363

**Comment by Finenyaco** [comment] 2024-01-19 11:26
**Environment**
- Walrus version: main 66a2214c8ea5dfb7fd8542fecb5e87a3778fc07e
- UI version: dev-7449733

**Test Result:** pass

Added the catalog name as the template prefix.

<img width="1873" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/005882b1-c580-4133-ba04-aaa5b4bb70b1">

**Closed by Finenyaco** 2024-01-19 11:26 UTC
Labels: bug
